name: sm_linter
description: Sua Música Linter Rules
version: 1.0.0
repository: https://github.com/SuaMusica/sm_linter
issue_tracker: https://github.com/SuaMusica/sm_linter/issues
homepage: https://github.com/SuaMusica/
documentation: https://

environment:
  sdk: '>=3.0.0 <4.0.0'
